### ISSUE TITLE
Why new versions depends on System.Memory, can it be a single dll?

### ISSUE THREAD

**Issue by equiclouds** [xoofx/markdig#549]
version from 0.19 add new depends System.Memory, While 0.18 and below have no depends, Can remove the depends by only using .NET48 classes?

**Comment by xoofx** [comment]
Not sure the impact but we want to remove support for .NET Framework at some point. It complicates the maintenance if we need to start to have ifdefs to support .NET FWK, as we have been trying to reduce the number of framework/.NET profiles we are using. So, if you really don't want System.Memory, stay on 0.18, otherwise upgrade.
