### ISSUE TITLE
Error in Markdown horizontal rule

### ISSUE THREAD

**Issue by NUnitTester** [xoofx/markdig#680]
`"Zeile 1\r\n---\r\nZeile 2"`
give wrong result
`"<h2 id="zeile-1">Zeile 1</h2>\n<p>Zeile 2</p>\n"`
instead of 
`"<p>Zeile 1</p>\n<hr />\n<p>Zeile 2</p>\n"`

This works
`"Zeile 1\r\n- - - - - - - -\r\nZeile 2"`

Example copied from here
[stackabuse](https://stackabuse.com/markdown-by-example)

**Comment by xoofx** [comment]
As per the spec for [setext](https://spec.commonmark.org/0.30/#example-103), this is expected (it is required a blank-line h1 otherwise it is interpreted as a settext). See also that all CommonMark compliant engine are producing the [same result](https://babelmark.github.io/?text=Zeile+1%0A---%0AZeile+2)

**Comment by NUnitTester** [comment]
Thanks for clearification
