### ISSUE TITLE
PipeTable is not parsed correctly

### ISSUE THREAD

**Issue by Nareznoy** [xoofx/markdig#747]
**Input markdown:**
```
Some paragraph:
|**Heading 1**|**Heading 2**|**Heading 3**|**Heading 4**|
|---|---|---|---|
|Value 1 |Value 2 |Value 3 | |
```

**Expected output HTML:**
```
<p>
   Some paragraph:
</p>
<table>
   <thead>
     <tr>
       <th>
         <strong>
           Heading 1
         </strong>
       </th>
       <th>
         <strong>
           Heading 2
         </strong>
       </th>
       <th>
         <strong>
           Heading 3
         </strong>
       </th>
       <th>
         <strong>
           Heading 4
         </strong>
       </th>
     </tr>
   </thead>
   <tbody>
     <tr>
       <td>
         Value 1
       </td>
       <td>
         Value 2
       </td>
       <td>
         Value 3
       </td>
       <td>
       </td>
     </tr>
   </tbody>
</table>
```

**Actual output HTML:**
```
<p>
   Some paragraph: |<strong>Heading 1
   </strong>|<strong>Heading 2
   </strong>|<strong>Heading 3
   </strong>|<strong>Heading 4
   </strong>| |---|---|---|---| |Value 1 |Value 2 |Value 3 | |
</p>

```

According to the CommonMark specification -- A sequence of non-blank lines **that cannot be interpreted as other kinds of blocks** forms a paragraph (https://spec.commonmark.org/0.30/#paragraphs). In this case, the table immediately following the paragraph **should be interpreted as a separate block**, but it is interpreted **as part of the paragraph** and, accordingly, is parsed incorrectly

**Comment by xoofx** [comment]
Because pipetables are not specified, there is a split in CommonMark implementations, and many are following the same behavior [here](https://babelmark.github.io/?text=Some+paragraph%3A%0A%7C**Heading+1**%7C**Heading+2**%7C**Heading+3**%7C**Heading+4**%7C%0A%7C---%7C---%7C---%7C---%7C%0A%7CValue+1+%7CValue+2+%7CValue+3+%7C+%7C)

Markdig requires a blank line before a table. It simplifies the parsing because we only have to test about a table at the beginning of a paragraph, not later.
